#!/bin/bash

cp -r usr/* /usr
cp -r etc/* /etc

cp -r home/user/* ~/.

chmod +x /usr/local/bin/install-opencart
chmod +x /usr/local/bin/install-opencart-plugin
chmod +x /usr/bin/install-opencart
chmod +x /usr/bin/install-opencart-plugin

echo "Install Complete"
exit 0
