#!/bin/bash

sudo cp -r usr/* /usr
sudo cp -r etc/* /etc
cp -r home/user/* ~/.

sudo chmod +x /usr/local/bin/install-opencart
sudo chmod +x /usr/local/bin/install-opencart-plugin

echo "Install Complete"
exit 0
